name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2      
      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wascap
        run: cargo install wascap --features "cli"
      - name: Build engine Provider
        run: cd engine-provider && cargo build --verbose --release
      - name: Build mech SDK
        run: cd mech-sdk && cargo test